### ISSUE TITLE
Failed to lookup the Enterprise ID for enterprise error

### ISSUE THREAD

**Issue by uskpea** [github/gh-gei#1007]
## Description
Unable to execute the 
![image](https://github.com/github/gh-gei/assets/88337031/27303a47-8561-466e-a77c-fe48f76f8d10)

gh gei migrate-org is not working and unable find an example to illustrate usage. It is getting an error Failed to lookup the Enterpirse ID.

[2023-05-26 16:35:54] [ERROR] Failed to lookup the Enterprise ID

**Comment by dylan-smith** [comment]
Does your GH_PAT environment variable have admin permissions on the target enterprise, and is SSO enabled (if you use SSO in the target enterprise).

**Comment by uskpea** [comment]
![image](https://github.com/github/gh-gei/assets/88337031/c9930ed9-f970-4de1-8c75-62e0e4fa7e00)
both source and target use the same PAT from target and try source and target use the same PAT from source.  When doing on gh gei migrate-repo, I used the PAT source for both and it seems to work.  However, the gh gei migrate-org does not and error with  [ERROR] Failed to lookup the Enterprise ID for enterprise

**Comment by uskpea** [comment]
Enterprise admin scoped issue - both source and target - the token must be scoped with Enterprise admin to perform gei migrate-org.

**Comment by uskpea** [comment]
Enterprise admin scoped permissions.
