### ISSUE TITLE
After GHES to GHEC migration the outputted text shows an incorrect extension name to download log

### ISSUE THREAD

**Issue by gitstua** [github/gh-gei#1033]
## Description

I completed a migration from GHES 3.7.4 to GHEC EMU and then tried to download the logs with the suggested command. This fails with the error `unknown command "gh-gei" for "gh"`

The correct command is `gh gei download-logs ...`

Mac OS 13.4 (22F66)
gei CLI [v0.45]

## Reproduction Steps
- complete single repo migration from GHES to GHEC EMU (I used GHEC 3.7.4)
- once completed the migration suggests running  downloading logs ```by running `gh gh-gei download-logs --github-target-org FOO --target-repo repo1```
-  an invalid command error is shown `unknown command "gh-gei" for "gh"`

**Comment by timrogers** [comment]
![image](https://github.com/github/gh-gei/assets/116134/69f4f876-2672-4be4-96e7-5bf9e9535dce)
