### ISSUE TITLE
Pull requests missing while migrating the repo's from ADO

### ISSUE THREAD

**Issue by bheemreddy181** [github/gh-gei#1035]
## Description

Pull requests missing while migrating the repo's

## Reproduction Steps

![Screenshot 2023-06-22 at 12 08 11 PM](https://github.com/github/gh-gei/assets/101338506/fd01fec1-0f39-4477-b326-c63f0058f519)
<img width="1451" alt="MicrosoftTeams-image (39)" src="https://github.com/github/gh-gei/assets/101338506/a0499299-7eee-4745-a4c1-f0989638ad49">
![MicrosoftTeams-image (40)](https://github.com/github/gh-gei/assets/101338506/98de9069-a590-48e4-bec8-647b0d4e3c4f)

**Comment by timrogers** [comment]
@bheemreddy181 Thanks for reaching out, and sorry that you're having issues with your migration. Since this is a backend issue rather than an issue in the open source CLI, could you please create a GitHub Support ticket? We can look into this for you.
