### ISSUE TITLE
Add an option to skip check for a new version.

### ISSUE THREAD

**Issue by tspascoal** [github/gh-gei#1077]
## Description

It would be nice to have an option to opt out of the version check, either with an environment variable or a `--skip-version-check` option.

This would allow skiping version checks when doing repo migrations at scale.

**Comment by dylan-smith** [comment]
If we do this, we should still have the CLI output the current version to make life easy for support folks looking at customer logs.

**Comment by timrogers** [comment]
Can you share a bit more information on why you want to skip the version check? Is it just to remove the overhead of the HTTP request?
