### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#117]
Make all commands idempotent so that if you call it more than once it will not fail. For example, create-team should check if the team already exists and if so show a warning (today it will just crash)
- [x] AddTeamToRepoCommand - This command is already Idempotent
- [x] #260 
- [x] #268 
- [x] #287
- [x] GenerateScriptCommand
- [x] GrantMigratorRoleCommand - This command is already Idempotent
- [ ] IntegrateBoardsCommand
- [x] LockRepoCommand - This command is already Idempotent
- [x] #333 
- [x] RevokeMigratorRoleCommand - This command is already Idempotent
- [ ] RewirePipelineCommand
- [x] #441

**Comment by slenguyen** [comment]
Closing old issue.
