### ISSUE TITLE
Internal error with migrate-repo from GitHub to GitHub Enterprise

### ISSUE THREAD

**Issue by jmaixl** [github/gh-gei#1201]
## Description

I ran:
```
gh gei migrate-repo --github-source-org ...
```

I received an error:
 ```
[2023-12-27 14:45:44] [ERROR] OctoshiftCLI.OctoshiftCliException: Something went wrong while executing your query. Please include `CD05:3369:2FA7B59:31B9679:658CA917` when reporting this issue.
```

I have been migrating repositories from 4-5 different sources, including the same source as used in this bug, to the same destination with no problem. I encountered this error today suddenly. Did something happen on the backend?

**Comment by timrogers** [comment]
@jmaixl Thanks for reaching out! I spotted that you closed this issue. Has the problem gone away?

**Comment by jmaixl** [comment]
Yes. It was an internal GitHub error with the API and codespaces.
