### ISSUE TITLE
PowerShell's convertfrom-json fails if there is non-English in gh api's output

### ISSUE THREAD

**Issue by kkamegawa** [github/gh-gei#1206]
## Description

When using `convertfrom-json` to convert the output of the `gh api` command in PowerShell on non-English Windows, non-English errors occur, not on Ubuntu 22.04.
gh version 2.42.0 (2024-01-11)

## Reproduction Steps

The commit messages in this repository contain Japanese characters, and when the output of the `gh api` command is converted using `convertfrom-json` in PowerShell 7.4 in a Japanese environment, an error occurs in the Japanese commit message.

**Error**: Windows 11 22H2(ja-jp) + PowerShell 7.4.0 + gh version 2.42.0 (2024-01-11)
```
❯ $json = gh api -H "Accept: application/vnd.github.v3+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/kkamegawa/felica2money/commits | convertfrom-json
ConvertFrom-Json: Conversion from JSON failed with error: After parsing a value an unexpected character was encountered: t. Path '[4].commit.message', line 1, position 14380.
```

**Success**: Windows 11 22H2(ja-jp) + PowerShell 7.4.0 
```
$header = @{
  Accept = "application/vnd.github+json" 
  'X-GitHub-Api-Version' = "2022-11-28"
}
$uri ='https://api.github.com/repos/kkamegawa/felica2money/commits'
$json = Invoke-RestMethod -Uri $Uri -Method Get -ContentType "application/json" -Headers $header
```

**Success**: Ubuntu 22.04(en-us) + PowerShell 7.4.0 + gh version 2.42.0 (2024-01-11)
```
PS /home/kkamegawa> $json = gh api -H "Accept: application/vnd.github.v3+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/kkamegawa/felica2money/commits | convertfrom-json
PS /home/kkamegawa>
```

**Comment by timrogers** [comment]
@kkamegawa Thanks for reaching out! It looks like this bug report is related to the GitHub CLI, not the GitHub Enterprise Importer extension. I'm going to transfer it to `cli/cli`.

**Comment by timrogers** [comment]
Actually, I can't transfer, so I'm gong to close this issue. Can you reopen it on https://github.com/cli/cli?
