### ISSUE TITLE
ado2gh migrate-repo optional overwrite of existing repo in github

### ISSUE THREAD

**Issue by rzr19** [github/gh-gei#1233]
Request for an optional flag to overwrite an existing repository at migrations from ADO to Github.
Encountered a situation where we need to migrate a main repo and its many forks with maintaining Main <> Fork relationship.

In short, we want to:
1st migrate the main repo(s), 
2nd recreate their N forks in github
3rd use GEI to migrate each of the forks in ADO to the preexisting forks from Github
4th have in github the main repos each with its list of forks in place as they were in ADO

At the current time attempts to use gh ado2gh migrate-repo with target name of a manually created fork, we get this warning:
`[WARNING] The Org 'x' already contains a repository with the name 'y'. No operation will be performed.`

**Comment by brianaj** [comment]
@rzr19 Migrations were designed to avoid migrating to existing repositories to prevent complications related to pre-existing data and settings. Have you thought about migrating a repository under a specific name within an organization, and then [transferring the repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)? Please be aware that if you're transferring between organizations, you must first reclaim all mannequins.

**Comment by rzr19** [comment]
@brianaj there is no option to transfer a repository as-is from an Azure DevOps organization to a GitHub organization.
That is what the ado2gh plugin does, hence my inquiry.

**Comment by brianaj** [comment]
Correct, I was suggesting after migrating the main repo and it's folks to try repo transfer to rebuild forked relationships. I'm not as familiar with repo transfer, but ado2gh does not migrate forked relationships as is and does not support migrating to an existing repo for reasons stated above.

**Comment by brianaj** [comment]
@rzr19 You can also try just doing a git clone/push of your forked repo to the existing fork you created in GitHub.

**Comment by rzr19** [comment]
@brianaj the clone/push with native git is our workaround at the moment.
At enterprise scale it overcomplicates what gei could do fairly easily.

Please reconsider in the future the optional --overwrite flag or another alternative for this edge case.

**Comment by klubi** [comment]
Hi
I have same case for bbs2gh.
At org level we manage GitHub repositories with terraform. Now, performing migration from BitBucket I'd like to first define an create my repos with terraform (bare minimum config), then migrate from BBS, and then add more complex config with terraform.
I can't do that, and doing it the other way around, where I have to first migrate repo, and then import it to terraform is rather tedious task.
Any chance for already mentioned `--overwrite` flag?
Thanks!
