### ISSUE TITLE
Request to use Github App instead of github Personal Access Token when using the bbs2gh gh cli extension

### ISSUE THREAD

**Issue by sd-bb-mig** [github/gh-gei#1260]
Hi Team,

Please note that, we are performing the migration of repositories from Bitbucket Server to Github server. In this process, we are using the Personal access token as per the below documentations.
- [Personal Access Tokens](https://docs.github.com/en/migrations/using-github-enterprise-importer/migrating-from-bitbucket-server-to-github-enterprise-cloud/managing-access-for-a-migration-from-bitbucket-server#required-scopes-for-personal-access-tokens)
- [Personal Access Token Scopes](https://docs.github.com/en/migrations/using-github-enterprise-importer/migrating-from-bitbucket-server-to-github-enterprise-cloud/managing-access-for-a-migration-from-bitbucket-server#required-scopes-for-personal-access-tokens)

We would like to use the Github App instead of the token so that it can be easily managed and we can control installations. Please let us know if this is possible so that we can plan on using Github Application.

Thanks and Regards,
Saravanan D

**Comment by ArinGhazarian** [comment]
👋 @sd-bb-mig,

GitHub app is not supported at this time so using a PAT is the only option.
