### ISSUE TITLE
Queries for API requests from logs

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#129]
Determine where the API request logs are for both the GitHub endpoints and the ADO endpoints. Figure out what queries we need against which systems (and what permissions we need) to get all the API requests made via the CLI. Should be able to filter by user-agent header.

**Comment by dylan-smith** [comment]
Would be useful to collect the CLI version number being used in our dashboard(s).

**Comment by ArinGhazarian** [comment]
### Summary
https://docs.google.com/document/d/1Q1TTerAfoTw3-LgDKpYNMJ4keH4DsY0GPyeoiXNCMec/edit?usp=sharing
