### ISSUE TITLE
GEI import from github.com to github.com stuck on  PENDING_VALIDATION

### ISSUE THREAD

**Issue by xs2bharat** [github/gh-gei#1296]
Using GEI import from github.com to github.com and import is tuck on PENDING_VALIDATION
![image](https://github.com/user-attachments/assets/d6762755-f703-49b4-b9be-d8cf36366822)

Tried deauthorizing PAT and reauthorizing PATs -it work randomly for 1 or 2 repos and stuck again.

**Comment by dacartr** [comment]
We are currently seeing the same issue, repositories stuck in PENDING_VALIDATION state.

 Command used `gh gei migrate-repo`, we've confirmed that both the origin and target PAT's are valid and have the right scopes assigend.

**Comment by xs2bharat** [comment]
I have opened support ticket with github, will update here. The ones which were stuck eventually got completed after 12 hours or last night

**Comment by dylan-smith** [comment]
We are aware of this issue and are working on a fix. In the meantime our engineers are taking manual steps to monitor and resolve stuck migrations.  If you want more communication on this, your best bet is to open a support ticket as this issue isn't being monitored by the engineers involved (it's not CLI related - which is all this repo is for). cc @iomekam

**Comment by dylan-smith** [comment]
We believe we have resolved this problem now. If you still see it please open a support ticket.
