### ISSUE TITLE
Extra metadata on API requests for telemetry

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#130]
Add metadata to API requests so we can determine which CLI command was calling each API endpoint. Ideally could add an extra HTTP header with the name of the CLI command. Alternatively, may be able to stuff some extra metadata in the user-agent header (if the logging system doesn't automatically capture all headers).

**Comment by ArinGhazarian** [comment]
Based on [this spike](https://github.com/github/gh-gei/issues/129) we need to leverage the `user-agent` header and add the CLI command (or any other meta data ) there.
