### ISSUE TITLE
BUG: bbs2gh migrate-repo --no-ssl-verify can only be provided with BBS Server URL While Providing the URL

### ISSUE THREAD

**Issue by ryaugusta** [github/gh-gei#1317]
## Description

I need to pass the `--no-ssl-verify` command when running the `migrate-repo` command but am seeing the error:
`[ERROR] --no-ssl-verify can only be provided with --bbs-server-url.`

I am passing the `--bbs-server-url` but this exception is still being caught for some reason;

My command:
```bash
gh bbs2gh migrate-repo \
  --archive-path <path-to-tar-file>.tar \
  --github-org GITHUB_ORG \
  --github-repo NEW_GITHUB_REPO \
  --bbs-server-url BBS_SERVER_URL \
  --bbs-project BBS_PROJECT \
  --bbs-repo BBS_REPO \
  --no-ssl-verify \
  --use-github-storage
```

I am providing the `--bbs-server-url`, which is the requirement to being able to use the `--no-ssl-verify` command.

Is there a way to install an older version of the bbs2gh extension so see if this bug arose from `v1.11.0`

## Reproduction Steps
Run the `gh bbs2gh migrate-repo` command and supply a bbs-server URL as well as `--no-ssl-verify`

**Comment by dylan-smith** [comment]
I think this error is correct. You are passing `--archive-path` meaning the migration will use the archive file you provide instead of calling BBS API's. Since it is not going to be calling BBS API's the `--no-ssl-verify` option is not applicable.

**Comment by ArinGhazarian** [comment]
Thanks for reporting, the error messages were updated in https://github.com/github/gh-gei/pull/1318

**Comment by ryaugusta** [comment]
Hi @dylan-smith & @ArinGhazarian 

Thanks for that bit of information. Since I'm giving the `--archive-path` option and my tar file, the tool shouldn't be calling the BBS API at all, however, I'm seeing in the logs of my workflow that the step the migration is failing on is `Error cloning source repo`.. in this case, the "source repo" is the BBS repository based on:

```bash
[2024-12-19 14:39:59] [DEBUG] RESPONSE (OK): {"data":{"node":{"id":"<<<MIGRATION_ID>>>","sourceUrl":"<<BITBUCKET_SERVER_URL>>","migrationLogUrl":".......=host","migrationSource":{"name":"Bitbucket Server Source"},"state":"FAILED","warningsCount":0,"failureReason":"Git source migration failed. Error message: A critical error occurred in the Clone Source step of the git migration.","repositoryName":"repo-migrated"}}}
```

Can you guys provide any more details for what's actually happening here? What are the API calls going out from the utility? Based on the docs I am expecting that if I provide the `--archive-path` that the GEI tool will just import the tar to GitHub blob storage, and then GH backend can reach the tar and upload it to my new GitHub repo for migration. 

If you can provide the steps involved, we've noticed in the logs there's an BBS API call trigger to clone the repo based on above error, as per the docs, we assume that we only need the tar & blob storage to perform the migration.

If the "Clone source repo" is referring to my repository in GitHub, I'm passing an authenticated PAT to the GEI why would it fail to clone?
