### ISSUE TITLE
Don's show the sensitive tokens (e.g. ADO PAT and GH_PAT) during the migration steps

### ISSUE THREAD

**Issue by bryantson** [github/gh-gei#169]
## Description

When running the migration, the values for `ADO_PAT` and `GH_PAT` are clearly printed out in the screen.

![image](https://user-images.githubusercontent.com/5396174/145094190-3dbf25e6-6aab-40d4-ba63-77e0893f5056.png)

## Reproduction Steps

1. Run the command `octoshift migrate` after everything is setup.
2. Notice that the values for `ADO_PAT` and `GH_PAT` print out

**Comment by dylan-smith** [comment]
that should only happen if you do --verbose

there is an issue to mask secrets in verbose logs (both in log files and on console #123 )

**Comment by bryantson** [comment]
Sounds good. Closing this issue but linking to:

https://github.com/github/gh-gei/issues/169#issuecomment-988220745
