### ISSUE TITLE
More options to configure generate-script behavior

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#21]
Default behavior should be to generate the minimum possible scripts - probably just the migrate-repo commands.

Then have optional arguments that can be passed to generate-script to add more functions to the generated script. E.g.:
--create-teams
--link-Idp-groups
--rewire-pipelines
--boards-integration
--lock-ado-repo
etc

This should involve the removal of the existing --repos-only flag

Possibly include a --all or something similar flag for customers that want to do all the things.

### Edit
Based on the below conversation we need to following options:
- [x] --create-teams
- [x] --link-idp-groups (also implies --create-teams)
- [x] --lock-ado-repos
- [x] --disable-ado-repos
- [x] --add-teams-to-repos
- [x] --integrate-boards
- [x] --rewire-pipelines
- [x] --all

**Comment by ArinGhazarian** [comment]
It looks like we need to have the following options:
- [ ] --create-teams
- [ ] --share-service-connections
- [ ] --lock-ado-repos
- [ ] --migrate-repos
- [ ] --disable-ado-repos
- [ ] --configure-autolinks
- [ ] --add-teams-to-repos
- [ ] --integrate-boards
- [ ] --rewire-pipelines
- [ ] --all

@dylan-smith I have two questions:
1. Do you agree with the option names? 
2. Do we even need the `--share-service-connections` ? I am guessing that it is a pre-requisite for rewiring pipelines right?

**Comment by dylan-smith** [comment]
That all looks pretty good I would make 3 changes

1. Get rid of --migrate-repos it should always do that
2. Get rid of --share-service-connection and include that logic in --rewire-pipeline
3. Get rid of --configure-autolink and include that logic in --integrate-boards
