### ISSUE TITLE
Sometimes integrate-boards requires All Orgs scope

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#216]
## Description

Home Point ran into a 401 error when calling integrate-boards. Changing their ADO PAT to have All Orgs scope fixed it.

However, when we tested and documented the scopes, All Orgs was not required. Why do some customers need All Orgs and others don't?

**Comment by modularity** [comment]
This might be from [linked remote work items](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=azure-devops&tabs=browser#link-to-a-remote-work-item) that span multiple Azure DevOps organizations.
