### ISSUE TITLE
Download migration logs across an organization

### ISSUE THREAD

**Issue by slenguyen** [github/gh-gei#230]
Create a cli command that calls the endpoint to gather all the organizational migration logs and download it

## Tasks

- [ ] Add a command to call the octoshift logic to generate organizational logs

## Dependencies

- https://github.com/github/octoshift/issues/3770

**Comment by dylan-smith** [comment]
I'd also suggest outputting the contents to the console, so the user can scroll through all the data without having to open up potentially many many separate text files.

**Comment by roferg** [comment]
> Is the motivation for this that the cli will be the only way/main way customers will run migrations for cross-org ? 

For now and into the foreseeable future the CLI will be our "UI" that we tell customers to use. 

> I'm thinking if we want to make this more general or cli specific. Also for maintainability, it would likely be easier if we had it be more general i.e. on the octoshift or github side

I'm not sure what the LEO difference is to put this on GitHub, but if it's similar to doing the work on the CLI I'm fine if we add an endpoint to GitHub to download these logs.

**Comment by slenguyen** [comment]
@roferg We're going to build this out on the Octoshift side and expose an endpoint to the cli! We'll repurpose this issue to handle that last bit.

**Comment by slenguyen** [comment]
This is a duplicate of #4380 and #3770.
