### ISSUE TITLE
Add a new command to check migration status

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#232]
## Description
So far the `migrate-repo` command would queue up a migration and wait for it to finish. In order to make repo migrations parallel, we need to queue up all repo migrations and wait for them one by one to finish. For that we need another command to check for the migration status of all repos.

## How it works
`wait-for-migration` command will query all migrations for an org and report the number of `in-progress` and `queued` ones (i.e `Total Migrations IN_PROGRESS: 2, Total Migrations QUEUED: 0 `), it exits when there is no more migration left in progress. It can also optionally take a `migration_id` as an argument, the only difference is that it will exit once the specified migration is either `failed` or `succeeded` but in each report cycle, will report the number of all `in-progress` or `queued` migrations just like the no arg variation.

**Comment by dylan-smith** [comment]
if it takes a migration id, and that migration fails, it should return a non-zero exit code.

**Comment by ArinGhazarian** [comment]
> if it takes a migration id, and that migration fails, it should return a non-zero exit code.

@dylan-smith my understanding is that the no arg variation should also return a non-zero code in case of any failed migration, no?

**Comment by dylan-smith** [comment]
no, I think we need a way to indicate that a migration failed. if there's no migrationid arg then it's irrelevant, but if we pass an id and it fails, we should return an exit code IMO
