### ISSUE TITLE
Improve test assertions on `MigrateRepoCommandTests`

### ISSUE THREAD

**Issue by juanmrad** [github/gh-gei#247]
based on: https://github.com/github/gh-gei/pull/236#discussion_r804268113

We want to improve the way the testing is structure for `GetMigrationState` in a way we can check that it gets called multiple times before it is successful. 

With `Moq` you can orchestrate the methods calls in such a way that with each call they return a different result as seen [here](https://github.com/Moq/moq4/wiki/Quickstart#miscellaneous)  That way we can test the flow for wait for status.

## Todo
- [ ] chain returns to check that method is called multiple times before happy path.

**Comment by dylan-smith** [comment]
can this be closed @juanmrad ?

**Comment by juanmrad** [comment]
@dylan-smith up you you. this was a recommendation from @ArinGhazarian when doing the repo command merge.

**Comment by dylan-smith** [comment]
oh ok, was just curious if the work was done in the linked PR or not? sounds like maybe not, so I'll leave it open if there's still work to be done here.
