### ISSUE TITLE
Need to add teams and users mapping, webhooks, tag protection, autolink, and email references as a part of migration

### ISSUE THREAD

**Issue by bryantson** [github/gh-gei#288]
## Description

Currently, GH-GEI does not migrate the followings:

- Teams mapping
- User Mapping ( mannequins )
- Webhooks ( working secrets included )
- Tag Protection
- AutoLink
- Email Reference

A customer requested that these should be eventually migrated from GHEC/GHEC-EMU to GHEC/GHEC-EMU path.

**Comment by bryantson** [comment]
User mapping should be addressed as a part of this PR

https://github.com/github/gh-gei/pull/271

**Comment by dylan-smith** [comment]
These would be more of a feature for the octoshift backend (with the possible exception of user mapping, which we're working on in the CLI).

Some of these will likely be included when we roll out org-level migrations for GH->GH. @roferg can hopefully comment on the rest. But I'm going to close this issue since I don't think these are things that are going to be handled in the CLI specifically.

**Comment by testworksau** [comment]
Hi @dylan-smith 👋🏼 

I noticed that a PR was merged that adds CLI support for Org to Org:
https://github.com/github/gh-gei/pull/591

Can you confirm which of the above should now be supported? Looking at the documentation, it seems a few of the above are currently listed as not being supported by the migration.

https://docs.github.com/en/enterprise-cloud@latest/early-access/enterprise-importer/understanding-github-enterprise-importer/migration-support-for-github-enterprise-importer#githubcom-migration-support

We're currently planning our migration from GHEC -> GHEC + EMU so just looking for clarity before we embark on our journey.

**Comment by andyfeller** [comment]
@testworksau : As @dylan-smith mentions above, I think https://github.com/github/octoshift/issues/4186 is the work on the backend to support recreating teams, however we can follow up with @slenguyen and @timrogers there to confirm 👍

**Comment by testworksau** [comment]
That would be great @andyfeller - I assume that's a private repository so won't be able to follow along.

Obviously would love to have this in place before we invest any effort in coming up with a migration script ourselves, however timing may not work out as we need to get our migration done sooner rather than later, in which case, so be it.

**Comment by timrogers** [comment]
@testworksau 👋🏻 Hey there! I'm the new PM. We're getting ready to launch org-to-org migrations. We're expecting it to be around the end of October. To start with, it will be fairly basic, just migrating teams and their permissions. Is that interesting to you? 

We plan to layer on more functionality - starting with fixing links between PRs and issues and organization settings - but that will come later.

**Comment by testworksau** [comment]
Hi @timrogers 👋🏼 

Thanks for this information. Yes, that would definitely be useful, the less scripts we have to write ourselves, the better!

I'm curious about the PR / Issue Link functionality - our plan is to:

- Migrate across to from `ourorg` to `ourorg-target`
- Rename `ourorg` to `ourorg-original`
- Rename `ourorg-target` to `ourorg` 

Would the links between PRs and Issues remain correct if we were to do the above?

**Comment by timrogers** [comment]
@testworksau 👋🏻 That would be expected to work, providing that you're moving between orgs on GitHub.com and not migrating from GHES to GHEC. Is that the case?

**Comment by testworksau** [comment]
Excellent, thanks for confirming @timrogers! We're going from GHEC to GHEC + EMU 😄

**Comment by ajmalmsali** [comment]
@timrogers is there a recommended way to do this for GHES to GHEC?

**Comment by timrogers** [comment]
@ajmalmsali Looking at the list above of things that aren't migrated, that list is still accurate for GHES to GHEC, with one exception - we do now migrate autolinks (full list of what we do and don't migrate [here](https://docs.github.com/en/migrations/using-github-enterprise-importer/understanding-github-enterprise-importer/migration-support-for-github-enterprise-importer#:~:text=GitHub%20Pages%20settings-,Autolink%20references,-GitHub%20Advanced%20Security)).

If you want to migrate data that isn't supported by our tools natively, your best bet would be to write scripts using the API to migrate that data. We are constantly working to make our tools better, though ✨
