### ISSUE TITLE
Support darwin-arm64 (i.e. M1 Macs)

### ISSUE THREAD

**Issue by mccannical** [github/gh-gei#302]
## Description
Please support gh-gei on m1 macbooks.

**Comment by dylan-smith** [comment]
good suggestion, we'll try to get to this soon

**Comment by dylan-smith** [comment]
Done! Will ship in next release of the CLI (probably on Monday)

**Comment by dylan-smith** [comment]
I had to

**Comment by dylan-smith** [comment]
It seems we're not the only ones to encounter this problem:
https://github.com/dotnet/runtime/issues/57242
https://github.com/dotnet/runtime/issues/57552

Talked with the GH CLI team also, and they are planning to implement some logic in the GH CLI that would check if Rosetta is present and if so fall back to the AMD64 binary. That would also fix this for folks with Rosetta installed.

Will keep this issue open, and try to revisit what is required to produce a working ARM64 binary of the CLI. The biggest challenge we have is no easy access to M1 macs to test. The GH Actions hosted pools do not include M1 macs yet.

**Comment by dylan-smith** [comment]
It looks like it's related to binary signing requirements on M1 macs that are not present on older macs.

I suspect if we built the mac binaries on our mac runner (even though its a non-M1 mac runner), it might work. I think dotnet will sign them automatically if it's being built on a mac.

**Comment by mccannical** [comment]
any news / updates on m1 support? did you get a chance to run on your mac runner?

**Comment by dylan-smith** [comment]
We're not planning on doing anything in the CLI for this right now, here is what customers can do to work around this limitation today, what we expect to happen in the near future to make the situation better, and the long-term plan to address it:

## Workaround Available Today
This repo publishes both the ado2gh and gei binaries as releases, with mac-arm64 versions available. While the GH CLI will fail trying to install the gei extension on M1 macs, you can still directly download and use the gei binary without the GH CLI (assuming you have Rosetta installed).

## Short-Term Plan
We've talked to the folks that own the GH CLI, and it sounds like they are going to add support for falling back to the AMD64 binary if the ARM64 one isn't available and the M1 machine has Rosetta installed.

## Long-Term Plan
Release M1-compatible ARM64 binaries. The main blocker to doing this today is the team doesn't have M1 macs readily available to test with. Hopefully GitHub Actions hosted runners will add support for M1 macs at some point and solve that problem for us.

**Comment by mislav** [comment]
The [latest GitHub CLI 2.8.0 release](https://github.com/cli/cli/releases/tag/v2.8.0) fixes this by falling back to `amd64` binary if Rosetta is installed. If an `arm64` binary is found, however, then its codesigning is fixed after downloading to allow execution by the OS.
