### ISSUE TITLE
Generate inventory-report for basic orgs.csv

### ISSUE THREAD

**Issue by DevStarOps** [github/gh-gei#310]
o	Org Name
o	Owner
o	Is PAT Project Collection Admin

**Comment by dylan-smith** [comment]
this API should be able to check whether a PAT has the collection admin role (although figuring out the exact args is tricky): https://docs.microsoft.com/en-us/rest/api/azure/devops/security/permissions/has-permissions?view=azure-devops-rest-6.0

**Comment by dylan-smith** [comment]
Move the Is PAT Collection Admin to a separate issue (#310)
