### ISSUE TITLE
Add `--target-api-url` to `gh gei` commands

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#375]
Right now for GHAE migrations, `gh gei` supports passing the `--target-api-url` to `migrate-repo` command to be able to make API calls against non default (`https://api.github.com`) bases addresses. The problem is that no other command in `gh gei` supports passing the `--target-api-url` in. We need to add the arg to all other `gh gei` commands and also make necessary changes to the `generate-script` command. 

## Todo
- [x] Add `--target-api-url` to all `gh gei` commands.
- [x] Modify `generate-script` to support passing the `--target-api-url` to `gh gei` commands.

**Comment by dylan-smith** [comment]
This should also be added to ado2gh

**Comment by dylan-smith** [comment]
Since we're no longer planning to support migrations TO GHAE I'm closing this issue.
