### ISSUE TITLE
Add docs for `--download-migration-logs` option to `generate-script` command

### ISSUE THREAD

**Issue by synthead** [github/gh-gei#383]
Introduced with https://github.com/github/gh-gei/pull/382!  Plese let the PR :point_left: for these options to be reviewed and merged before starting this issue, as the options may change :sparkles: 

Add documentation for the `--download-migration-logs` option to `generate-script` command.

Truncated help page from `gei generate-script --help` with this new option:

```
generate-script
  Generates a migration script. This provides you the ability to review the steps that this tool will take, and 
  optionally modify the script if desired before running it.

Usage:
  gei [options] generate-script

Options:
  ...
  --download-migration-logs                           Downloads the migration log for for each repostiory 
                                                      migration.
  ...
```

**Comment by timrogers** [comment]
Already documented: https://docs.github.com/en/migrations/using-github-enterprise-importer/completing-your-migration-with-github-enterprise-importer/accessing-your-migration-logs-for-github-enterprise-importer#downloading-all-the-repository-migration-logs-for-a-migration-script
