### ISSUE TITLE
Lock Repo command for GH->GH migration

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#385]
Introduce a `lock-repo` command to `gei` that works similar to the lock-ado-repo command in `ado2gh`.

Should also update the `generate-script` command in `gei` to optionally include `lock-repo` in the generated script. This should also follow the design established in `ado2gh generate-script` where we already have this option. For `gh gei generate-script` we only need to support `lock-repo` when generating a GH->GH script, if customers want a more advanced ADO->GH script they should be using `ado2gh generate-script`.

Note: These changes should probably be split into separate PR's.

**Comment by andyfeller** [comment]
@dylan-smith : so just to clarify with GEI today, customers would need to coordinate locking the source repositories while they're being migrated, right?

**Comment by dylan-smith** [comment]
> @dylan-smith : so just to clarify with GEI today, customers would need to coordinate locking the source repositories while they're being migrated, right?

that's correct

**Comment by robandpdx** [comment]
It would be great if `gh gei migrate-repo` took an option to lock the repo and simply pass that option to the graphql api [here](https://github.com/github/gh-gei/blob/d4db664df9cf1f2dd6ee8df20ce9265bb79ff1c8/src/Octoshift/GithubApi.cs#L215), assuming the graphql api supports such an option.
