### ISSUE TITLE
Migrate inactive webhooks

### ISSUE THREAD

**Issue by cvega** [github/gh-gei#411]
## Description

If a webhook is disabled it will not be migrated. All webhooks should be migrated regardless of active/disabled status. Additional reporting in the issue regarding inactive webhooks would also be a nice to have.

**Comment by dylan-smith** [comment]
@cvega I assume you're talking about GHEC->GHEC migrations?

This would need to be implemented in the backend, adding @roferg

**Comment by roferg** [comment]
@cvega - Can you tell me more about the customer ask and scenario for moving inactive web hooks? I'm assuming this is Salesforce?

**Comment by cvega** [comment]
@roferg No, problem. Basically the customer was confused when the inactive webhooks did not come over, also I suspect some of these webhooks may be set as inactive pre migration.

**Comment by toddoconnor** [comment]
I am the customer. We are performing GHEC->GHEC w/EMU migrations. How about an option to migrate all hooks instead? I can see that some users might not want the disabled hooks as they are no longer in use. In that case I'd say delete the hook. In our case the hook might be temporarily disabled but used in the future. We wouldn't want to leave it active and constantly fail. 

Maybe an option `--migrate-all-webhooks` would be useful.

**Comment by roferg** [comment]
@toddoconnor - Thanks for the input! We're looking at expanding what can be migrated to include all webhooks. It don't have an ETA that this point yet.

**Comment by dylan-smith** [comment]
being implemented in this PR: https://github.com/github/github/pull/225444

**Comment by roferg** [comment]
@toddoconnor - We have a PR in the works to migrate disabled webhooks as well. I'm hopeful we can get it deployed next week.
