### ISSUE TITLE
Migrating repo currently does not support migration of all collaborators and teams settings

### ISSUE THREAD

**Issue by bryantson** [github/gh-gei#430]
## Description

When I run the following command:

```sh
gh gei migrate-repo --github-source-org "${GH_SOURCE_ORG}" --github-target-org "${GH_ORG}" \
    --source-repo "<source repo name>"  --target-repo "<target repo name>" \
    --github-target-pat "${GH_PAT}" --github-source-pat "${GH_SOURCE_PAT}" \
    --verbose --wait
```

It does not migrate all permissions as one can found from **Settings** then **Teams** under **Access** but only service account.

Is this currently not implemented?

**Comment by dylan-smith** [comment]
I believe this capability will come with org-level migrations (a future planned feature). @roferg can confirm

**Comment by roferg** [comment]
This is coming when we enable migrations to be run on an org-by-org basis as well.

**Comment by testworksau** [comment]
Hi @dylan-smith @roferg 👋🏼 

I noticed that a PR was merged that adds CLI support for Org to Org:
https://github.com/github/gh-gei/pull/591

Can you confirm whether migration of permissions is now supported?

**Comment by dylan-smith** [comment]
It is not currently supported. Org to Org is a capability we are working on, but not available for customers to use yet.
