### ISSUE TITLE
The command "generate-script" generates invalid commands when original repo name has invalid characters

### ISSUE THREAD

**Issue by martins-vds** [github/gh-gei#444]
## Description

The command "generate-script" generates invalid commands when the ADO repository name has characters that are not valid for repository names on GitHub.

## Reproduction Steps

- Create a repository on Azure DevOps and name it anything as long as the name has spaces or any other invalid character in it, for example, "Parts Unlimited".
- Run the command "ado2gh generate-script" command with the "--all" switch
- Migrate.ps1 will look like the script below
```posh
#!/usr/bin/env pwsh

# =========== Created with CLI version 0.18.0.0 ===========

function Exec {
    param (
        [scriptblock]$ScriptBlock
    )
    & @ScriptBlock
    if ($lastexitcode -ne 0) {
        exit $lastexitcode
    }
}
# =========== Organization: <ADO_ORG> ===========

# === Team Project: <ADO_ORG>/Parts Unlimited ===
Exec { ./ado2gh create-team --github-org "<GH_ORG>" --team-name "Parts Unlimited-Maintainers" }
Exec { ./ado2gh create-team --github-org "<GH_ORG>" --team-name "Parts Unlimited-Admins" }
Exec { ./ado2gh share-service-connection --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --service-connection-id "<SERVICE_CONNECTION_ID>" }

Exec { ./ado2gh lock-ado-repo --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-repo "PartsUnlimited" }
Exec { ./ado2gh migrate-repo --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-repo "PartsUnlimited" --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --wait }
Exec { ./ado2gh disable-ado-repo --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-repo "PartsUnlimited" }
Exec { ./ado2gh configure-autolink --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" }
Exec { ./ado2gh add-team-to-repo --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --team "Parts Unlimited-Maintainers" --role "maintain" }
Exec { ./ado2gh add-team-to-repo --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --team "Parts Unlimited-Admins" --role "admin" }
Exec { ./ado2gh integrate-boards --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" }
Exec { ./ado2gh download-logs --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" }
Exec { ./ado2gh rewire-pipeline --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-pipeline "\PartsUnlimitedE2E" --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --service-connection-id "<SERVICE_CONNECTION_ID>" }
```
- Notice the white spaces in "Parts Unlimited-PartsUnlimited" in the "--github-repo" switches all over the script
- This repo will be imported with the normalized name `Parts-Unlimited-PartsUnlimited` (without spaces and possibly other invalid characters) which is different from `Parts Unlimited-PartsUnlimited` (with spaces and possibly other invalid characters) so all the commands that use the incorrect name fail, for example, the command "configure-autolink".

![image](https://user-images.githubusercontent.com/41807230/173469537-d303710c-225a-4312-8e49-43679681e9fe.png)

**Comment by dylan-smith** [comment]
Good catch, we'll prioritize fixing this ASAP

**Comment by dylan-smith** [comment]
It looks like the problem (at least if we only consider spaces) is when a Team Project has a space in it right? because the existing code handles repo names with spaces I thought.

**Comment by martins-vds** [comment]
The code handles repo names with spaces only but doesn't handle other invalid characters.
