### ISSUE TITLE
`generate-mannequin-csv` misses a lot of users

### ISSUE THREAD

**Issue by toddoconnor** [github/gh-gei#457]
## Description

After migrating repos, running the `gh gei generate-mannequin-csv --github-target-org ORGNAME` produces a very small CSV with many users from the source ORG missing. I would expect all users present in the source ORG to be present in the CSV for possible mannequin remapping. This is not so.

## Reproduction Steps

As an Org Owner with a PAT with all scopes selected, run `gh gei generate-mannequin-csv --github-target-org ORGNAME` to produce the mannequin CSV file. Notice the file is missing users that have performed work in the repos in ORGNAME.

**Comment by dylan-smith** [comment]
Hi @toddoconnor 

Can you go to the Organization Settings for the target org, and look on the Import/Export tab. It should show you the list of mannequins. Can you let me know what that list looks like? does it match the CSV?

![image](https://user-images.githubusercontent.com/1508559/174848214-ec25c18d-bfdf-41c5-a8af-385203832cc9.png)

**Comment by toddoconnor** [comment]
Hi @dylan-smith 

Yes, the Import/Export page does show two mannequin users which are the same two in the CSV file. 

However, if I look through the repo's commit history there are many users that have made pushes which I would expect to show up in the CSV file as well for mannequin reclamation.

**Comment by roferg** [comment]
@toddoconnor - There is actually a difference in how identities are handled during migration when dealing with Git commit data and the rest of the experiences in GitHub. 

GEI doesn't modify any Git data as part of a migration. Effectively we just do a mirror clone, change remote, and push as part of the migration. The actual user history for commits is driven off what a user configures their `user.name` and `user.email` settings locally in the Git CLI. GitHub uses the email property to align the authorship with a GitHub user that has the same email confirmed on their account. 

We have more details on this [here](https://docs.github.com/en/early-access/github/migrating-with-github-enterprise-importer/running-a-migration-with-github-enterprise-importer/reclaiming-mannequins#about-mannequins) in the migration documentation. As well as links to resources for GitHub.com with situations where the commit history isn't showing up in a user's profile. 

![image](https://user-images.githubusercontent.com/40493721/174859845-ffdc9325-375e-41ae-a92a-4ac1d8351160.png)

**Comment by toddoconnor** [comment]
@roferg After further testing this is isolated to the commit history. I do see the mannequin label in Issues and PRs.
