### ISSUE TITLE
Items not migrated when performing GHEC > GHEC w/EMU repo migration

### ISSUE THREAD

**Issue by toddoconnor** [github/gh-gei#458]
## Description

In spot checking GHEC > GHEC w/EMU repo migrations I have discovered that the following items are not migrated.

- Custom Team & member roles (settings/role_details)
- Protected Tags (settings/tag_protection)
- Disabled webhooks _(known - see #411 )_
- notifications (settings/notifications)
- Secrets under both Actions and Dependabot
- Environments (settings/environments) other than GH Pages which is migrated
- Autolink references (settings/key_links)
- Discussions
- Actions settings (custom Artifact and log retention setting - not migrated)
- Deploy keys
- Some General settings missed
   - Require contributors to sign off on web-based commits
   - Default to PR title for squash merge commits
- Pinned Repository (if a repo was pinned on the source, it is not on the target) _(this is an Org setting so understood why this is missing)_

## Reproduction Steps

I am an Org owner on both the source and target Orgs. Both PATs have all scopes selected. Using a generated script to perform the repo migrations. Spot check the target repo and see what is missing/different from the source repo.

**Comment by bobby-lin-cdc** [comment]
Hi @dylan-smith , are there plans to support the migration of discussion items?

**Comment by dylan-smith** [comment]
There is some work going on in the GEI backend repo to improve support for large repos/refspecs. The workaround you're talking about you'll need to use the GraphQL API directly today, as you're right the CLI doesn't support providing just a metadata archive (at least we certainly haven't tested that scenario).

cc @timrogers to decide if adding support for that to the CLI is something we'd want to consider.

**Comment by testworksau** [comment]
@dylan-smith is the workaround (using GraphQL API directly) documented anywhere? 

I've found this link:
https://docs.github.com/en/early-access/enterprise-importer/migrating-repositories-with-github-enterprise-importer/migrating-repositories-from-githubcom-to-github-enterprise-cloud?tool=api

but suspect that will do the same thing as the CLI will do; I need to be able to generate and then upload a metadata archive for a given repo, right?

**Comment by timrogers** [comment]
@testworksau 👋 At the moment, unfortunately, there isn't a workaround that will work for your use case. There isn't a way to "bring your own Git data" and then layer the metadata on top. This is something that we will consider for future development though.

We have some work planned next quarter to rework how we do the Git migrations, and it's quite possible that this will allow us to push a repo like yours, but hard to guarantee.

Sorry for giving you the answer you don't want!

**Comment by testworksau** [comment]
No worries - thanks for the update in any case @timrogers

**Comment by timrogers** [comment]
Closing this as, whilst we recognise the gaps identified, they're changes we need to make on the migrations backend, not in the CLI itself. Rest assured that these needs are known, and we do care!
