### ISSUE TITLE
Better error handling if startRepositoryMigration fails

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#464]
Recently startRepositoryMigration endpoint implemented some pre-migration validation. If the validation fails (e.g. workflow scope missing), the API call to startRepositoryMigration will not return a migration ID and will instead return an error message (but still an HTTP 200).

Right now this will cause the CLI to crash, because when it gets a 200 response it expects to find a migration ID.

It would be better to look for the error message in the response, and raise an OctoshiftCliException.

You can see an example of this failure here: https://github.com/github/gh-gei/runs/6995914753?check_suite_focus=true#step:17:168

**Comment by Jesson1018** [comment]
How can we get a migration ID?
