### ISSUE TITLE
GEI CLI reports 301 and won't queue a migration for a recently renamed repo

### ISSUE THREAD

**Issue by roferg** [github/gh-gei#469]
## Description

The GEI CLI checks if a repo name is already in use before calling the GEI backend to queue a migration. If you rename a repo instead of deleting it then you end up with a 301 response when trying to queue a migration. Which stops the CLI from moving forward. 

## Reproduction Steps

1. Migrate a repo. For example, migrate a repo into a new repo called `foo`. 
2. Rename that repo after the migration completes. For example, rename `foo` to `foo-1`. 
3. Try to queue the migration again with the original repo name as the target. For example, try to migrate into `foo` again. 
4. Note that the CLI errors out on the 301 response from GitHub.

**Comment by dylan-smith** [comment]
I think removing the when clause on this line should fix it: https://github.com/github/gh-gei/blob/6365933024e905e1fa5d2d9396e30c32a8a27fa9/src/Octoshift/GithubApi.cs#L109

**Comment by ArinGhazarian** [comment]
I think it's better not to swallow all exceptions and just modify the `when` clause to include `HttpStatusCode.Moved`)
