### ISSUE TITLE
Migration resulted in emails about closed PRs

### ISSUE THREAD

**Issue by toddoconnor** [github/gh-gei#475]
I performed a GHEC to GHEC w/EMU migration and the repo in question had both open and closed PRs. Users reported receiving emails about closed PRs from the new EMU org/repo. This took us by surprise.

The From: address was also very poor. Only after looking at the Subject: field where the unique EMU org name was mentioned (as well as the closed PR number) could we tell where the message was coming from. 

Is this expected that closed PRs would generate email after a migration?

**Comment by dylan-smith** [comment]
Hi @toddoconnor, I suggest creating a support ticket as that will ensure this gets in front of the appropriate people. I did let them know in our internal slack channel, but a support ticket is the best way to ensure somebody follows up with you ASAP.

**Comment by toddoconnor** [comment]
Hi @dylan-smith Ticket has been opened in our support queue. Thanks!
