### ISSUE TITLE
rewire-pipeline for cases where default branch has changed in destination repo

### ISSUE THREAD

**Issue by badbort** [github/gh-gei#484]
## Description

I am working on some automation for migrating from azdo to gh and ran into a hiccup when I realised that most repos that will be migrated use `master` default branch when the destination repository uses `main`.

To give some context as to why the default branch is different: I'm not using the GitHub importer. I'm essentially merging the existing AzDO repo into a new GitHub repo (provisioned by terraform) with --allow-unrelated-histories.

## Proposal

Add `--default-branch` option to the `rewire-pipeline` command.

Working on a PR at the moment and will link this issue

**Comment by dylan-smith** [comment]
I've been trying to decide whether it's a good idea to include functionality like this in the CLI. In general this CLI is meant to be for customers that are using GEI to migrate their repos. This functionality is for a different scenario, where you are migrating the repo with a non-GEI method, but want to use some of the other commands in this CLI (e.g. rewire-pipeline).

**Comment by dylan-smith** [comment]
Hi @badbort . We discussed this internally and decided that for now we want to keep the CLI focused on GEI migration scenarios.

If you want to use our code as a starting point for your customizations I'd suggest forking our repo and going from there.

**Comment by badbort** [comment]
Fair enough, I agree it does fall outside the scope of of the GEI.
