### ISSUE TITLE
Add rate-limit intelligence to our GitHub API calls

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#494]
When we call Azure DevOps API's we look at and respect the rate limit headers returned, but we don't do the same thing for GitHub rate limits.

We should be looking at the [GitHub Rate Limit HTTP Response Headers](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limit-http-headers) and logging/warning the user when the limit is close or hit, and waiting until the limit resets before making more API calls.

**Comment by roferg** [comment]
When a customer queueing migrations hits a rate limit, the CLI should wait until the rate limit refreshes. During this time it should display a message to a customer that it's waiting.
