### ISSUE TITLE
Redirect Logs

### ISSUE THREAD

**Issue by DaveKLloyd** [github/gh-gei#509]
## I would like more control over the Log files

Perhaps this is possible and I just don't know how. 

It would be nice to be able to re-direct the logs to be created in another folder. 

ado2gh migrate-repo bla bla bla  **--logpath  ".\Logs"**

Dave

**Comment by dylan-smith** [comment]
We have an issue for improving the "log sprawl" problem we know we have. Can I get you to add your suggestion to that issue. It's undecided what we'll do, but we do plan to do something when time permits.

https://github.com/github/gh-gei/issues/120
