### ISSUE TITLE
gei - generate-script - possibility to generate multiples migrate.ps1 files

### ISSUE THREAD

**Issue by AlexandreODelisle** [github/gh-gei#521]
## Description

Would it be possible to have a flag to enable us to have smaller amount of repositories in a  `migrate.ps1`. 

I would think of a flag as `–-migration-chunk 500` that would enable us to have multiple files of the powershell script in order to minimize the script of in the middle failure, and easing the retake of a migration ( having smaller of elements to migrate at once ) 

Eg for an Organization of 4000 repositories with a `–-migration-chunk 500` we would have 8 files as `migrate_1.ps1, migrate_2.ps1, ... `

**Comment by toddoconnor** [comment]
I concur. I could take advantage of this as well with as many repos. Nice suggestion @AlexandreODelisle .

**Comment by dylan-smith** [comment]
Our plan for this is to do something similar to what we did with migrations from ADO->GH. There is an `inventory-report` command that will generate a repos.csv file with a list of all your repos and some useful info (# of PR's, last push date, etc).

Then we would update `generate-script` to accept a repos.csv file as input. That way you could generate a repos.csv file, then slice it up however you desired. Then feed each csv file into `generate-script` to generate multiple migration scripts for each desired batch.

The work to do this is being tracked in this issue: #493 

Let me know if this would be a good solution, and if so I'll close this issue in favor of the other one.

**Comment by AlexandreODelisle** [comment]
@dylan-smith , yes this feature could do it indeed. 

For the time being, with made a work around to handle it for the gh -> gh migration. 

Thanks,
