### ISSUE TITLE
gei - generate-script - possibility to sort the repository by an attribute

### ISSUE THREAD

**Issue by AlexandreODelisle** [github/gh-gei#522]
## Description

In order to prioritize a large migration of an Organization it would be great to be able to pass a flag with a key name in order to sort the repository list in accordance with the provided flag, example `--sorted-repos-by pushed_at`

The key I am thinking about, is `pushed_at`, it is an attibute returned by the API when we get a list of repositories. 

It would enable the migration to prioritize repositories by order of usage ( if we may say so ),  Organization with large amount of repositories need to be able to reduce the downtime to the active users. Having of `migrate.ps1` repositories sorted would help in the manner.

**Comment by dylan-smith** [comment]
Our plan for this is to do something similar to what we did with migrations from ADO->GH. There is an `inventory-report` command that will generate a repos.csv file with a list of all your repos and some useful info (# of PR's, last push date, etc).

Then we would update `generate-script` to accept a repos.csv file as input. That way you could sort the repos.csv file using whatever sorting logic you want (we'd have to ensure `inventory-report` includes the appropriate fields to sort by). Then feed the sorted csv file into `generate-script` to create a migration script with the right repos in the right order.

The work to do this is being tracked in this issue: https://github.com/github/gh-gei/issues/493

Let me know if this would be a good solution, and if so I'll close this issue in favor of the other one.

**Comment by AlexandreODelisle** [comment]
@dylan-smith, yes this feature could do it indeed.

For the time being, with made a work around to handle it for the gh -> gh migration.

Thanks,
