### ISSUE TITLE
Retry GHES archive generation

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#611]
We've been seeing a bunch of integration test failures when generating GHES archives. Usually the error is something like the connection was closed, or other networking sounding errors.

We could probably do a retry on archive generation if it fails for any reason.

**Comment by dylan-smith** [comment]
We have already added retries on HTTP failures. But sometime the archive generation might fail, but GHES returns an HTTP 200 with a message telling us the archive generation failed. In that case we should restart the archive generation again.

**Comment by timrogers** [comment]
This issue was mentioned in FastTrack's CarMax [trip report](https://github.com/github/FastTrack/blob/89a3644980274934d11d70a0d13fea24db81df59/Engagement/457-carmax/tripreport.md).

**Comment by dylan-smith** [comment]
I don't think the PR does what this issue intended.

The intent behind the issue was that if archive generation fails for pretty much any reason (network error, GHES says it failed on it's side, etc), the CLI would just start the whole archive generation process over. And it would do that 5 times before finally giving up. However, with that PR's change I think all that happens is if GHES returns the FAILED status code, the CLI will retry the GetMigrationStatus api call a few times (presumably always getting the same Migration_Failed response).

I'm going to re-open this Issue.
