### ISSUE TITLE
Need to reclaim mannequins multiple time?

### ISSUE THREAD

**Issue by ystndr** [github/gh-gei#613]
## Description

I migrated a `RepoA`, I reclaimed the mannequin of `UserA-ADO` (mannequin-user) to `UserA-GH` (target-user).
When I migrate a `RepoB`, I still see `UserA-ADO` as a mannequin, whereas I thought it should become `UserA-GH` because it is in the same organization and has been reclaimed before.

Is this an expected behavior? 

## Reproduction Steps

- Migrate one repo, reclaim a user
- Migrate another repo (that has the same user which was reclaimed in previous repo)
- See if the user is not reclaimed in the latter repo

**Comment by dylan-smith** [comment]
that sounds like a bug to me! However, the bug would be in the migrations backend and this repo is only for the CLI part of our migration tooling (the backend isn't OSS).

Can I ask you to create a support ticket with github with this same information, and that will get routed to the right team to fix the bug. Thanks!
