### ISSUE TITLE
Remove ADO specific args from `gh gei`

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#614]
Currently all ADO specific args in the `gh gei` are marked as hidden. At some point in the future (lets say a month or so down the road), once customers have had enough time to upgrade, we'll delete the ADO arguments and code paths entirely from `gei`.

## Dependencies
#624

**Comment by dylan-smith** [comment]
@timrogers you put this in Up Next but it has a dependency on #624 so I'm assuming they should both be Up Next.

**Comment by timrogers** [comment]
PR is ready to go, but we are letting Philips know that the change is coming, with ~2 weeks notice.
