### ISSUE TITLE
ado2gh migrate script not working without modification

### ISSUE THREAD

**Issue by AnttiHal** [github/gh-gei#657]
## Description
I installed ado2gh extension with command `gh extension install github/gh-ado2gh` and after that I created migration-script with command `gh ado2gh generate-script --ado-org SOURCE --github-org DESTINATION --output FILENAME`.
However, when trying to run the generated [script] I got this error: 
<img width="775" alt="Screenshot 2022-09-23 at 13 11 29" src="https://user-images.githubusercontent.com/48278195/191939409-d81037fb-aa71-4316-b47a-658f8abc9a1a.png">

I replaced `./ado2gh` with `ga ado2gh` in every place it was in the script and it started working.
It seems that `./ado2gh` is hardcoded here: [https://github.com/github/gh-gei/blob/main/src/ado2gh/Handlers/GenerateScriptCommandHandler.cs](url) in several places.
I'm not an expert with these but I hope this is helpful.

**Comment by dylan-smith** [comment]
This is an embarrassing one. Thanks for reporting @AnttiHal . We fairly recently switched ado2gh from being a stand-alone CLI to an extension to the `gh` CLI. And we must have missed changing how it's called in the generated script. I'm going to push a fix for this right now, and I plan to release a new version on Monday with this change.

What you did is the proper work-around.

**Comment by dylan-smith** [comment]
The fix is now merged into main (#661 )

We prefer not to publish new releases on Fridays, so I'll create a new release on Monday with this fix.

**Comment by AnttiHal** [comment]
Also I noticed that in the official documentation there's wrong command on "generating a migration script" section. There is `gh ado2gh generate-script --ado-source-org SOURCE --github-target-org DESTINATION --output FILENAME` but should be this: `gh ado2gh generate-script --ado-org SOURCE --github-org DESTINATION --output FILENAME`.
[https://docs.github.com/en/early-access/enterprise-importer/migrating-repositories-with-github-enterprise-importer/migrating-repositories-to-github-enterprise-cloud/migrating-repositories-from-azure-devops-to-github-enterprise-cloud#generating-a-migration-script](url)
