### ISSUE TITLE
gh gei download-logs does not seem to work when in a batched migration

### ISSUE THREAD

**Issue by testworksau** [github/gh-gei#688]
## Description

Logs are always downloaded fine with a single migration. However, today, I found that the `gh gei download-logs` command does not seem to work when run in a batched migration. 

I've been running individual migrations over the past couple of weeks, and have been using the generated commands to download the logs after each individual repo migration.

e.g. running this command:

```
gh gei generate-script --github-source-org org1 --github-target-org org2 --download-migration-logs
```

and then pulling individual repo migrations out into separate migration scripts, e.g.

```
$MigrationID = ExecAndGetMigrationID { gh gei migrate-repo --github-source-org "org1" --source-repo "repo1" --github-target-org "org2" --target-repo "repo1" }
$RepoMigrations["repo1"] = $MigrationID

gh gei wait-for-migration --migration-id $RepoMigrations["repo1"]
if ($lastexitcode -eq 0) { $Succeeded++ } else { $Failed++ }
gh gei download-logs --github-target-org "org2" --target-repo "repo1"
```

I ran a migration against a sandpit organisation that contained 17 repositories, which queued up all repositories first (as per the generated file) before proceeding to check each migration. 

The migration took 27 minutes, and only the last two logs could be downloaded; the rest had a message such as:

```
[2:36 pm] [INFO] Waiting for repo1 migration (ID: RM_<a_long_string>) to finish...
[2:36 pm] [INFO] Migration <a_long_string> succeeded for repo1
[2:36 pm] [INFO] You are running the latest version of the gei CLI [v0.28]
[2:36 pm] [WARNING] Migration logs are only available for 24 hours after a migration finishes!
[2:36 pm] [INFO] Downloading migration logs...
[2:36 pm] [INFO] GITHUB ORG: org2
[2:36 pm] [INFO] GITHUB REPO: repo1
[2:36 pm] [ERROR] Migration for repository repo1 not found!
```

Only the last two repositories managed to successfully download the migration log.

**Comment by dylan-smith** [comment]
I know there's an open support ticket for this (which is the appropriate thing to do here). I'm going to leave this open for now and update once I see what the resolution to the support ticket was.
