### ISSUE TITLE
Add support for Security Token Service (STS)-provided temporary security credentials for S3 blob storage

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#692]
We now allow users to use Amazon S3 for blob storage when migrating from GitHub Enterprise Server.

When calling the CLI, we accept an AWS access key, secret key and bucket name. This works well if using standard AWS IAM credentials tied to a user. 

But it doesn't work if you want to use temporary security credentials provided by AWS Security Token Service (STS) for security reasons.

We should allow these to be used with the CLI. A basic solution would just be to accept [the session token that goes with the access key and secret key in the STS case](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/prog-services-sts.html). A more complex solution could conceivably generate credentials for you.

**Comment by mattbryce93** [comment]
I've created this pull request that I believe would address this, I'm quite unfamiliar with c# so any assistance with tests and checking my code would be appreciated: https://github.com/github/gh-gei/pull/725

**Comment by dylan-smith** [comment]
Hi @mattbryce93, thanks for trying to contribute! Unfortunately, it looks like your PR needs a lot more work before we could consider accepting it (e.g. it doesn't compile, doesn't pass the linter, I suspect it breaks existing scenarios, and is missing a bunch of things needed to support the STS scenario such as new args).

My best suggestion would be to find a friend that knows a bit more c# to help out, or wait until this backlog item raises to the top of our teams priority list and we can help tackle it.

**Comment by timrogers** [comment]
Fixed by #844.
