### ISSUE TITLE
Update generate-script docs

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#695]
As part of #682 we removed `--azure-storage-connection-string` option from the `generate-script` command. We also introduced AWS S3 bucket name (`--aws-bucket-name`) as a new args to support S3 upload as an altrernative to Azure storage. Like Azure storage, the secrets for S3 (`--aws-secret-key` and `--aws-access-key`) need to be set as environment variables or directly provided to `migrate-repo` command for the S3 upload to work.

## Todo
- [ ] Update [generate migration script doc](https://docs.github.com/en/early-access/enterprise-importer/migrating-repositories-with-github-enterprise-importer/migrating-repositories-to-github-enterprise-cloud/migrating-repositories-from-github-enterprise-server-to-github-enterprise-cloud#generating-a-migration-script) to reflect removed and added options.

**Comment by timrogers** [comment]
Done!
