### ISSUE TITLE
Support GHES to GHAE migration

### ISSUE THREAD

**Issue by lmk-anz** [github/gh-gei#697]
## Description

I've been testing using the latest version of `gh-gei` (0.28) a test migration (using `generate-script`) of an org/repo from an on premises GHE instance (running 3.4.9) to GHAE (I think our GHAE is running 3.3.x).

So far the issues I have encountered are:

* No ability to specify `--github-target-pat` when using `gh gei generate-script`.
  I noticed that if I use `GH_PAT` and `--github-source-pat`, that param doesn't work (so I suspect `GH_PAT` is overriding it).

I hand edited the migration script as the target is assumed to be `github.com` instead of `COMPANY.ghe.com`, and added `--target-api-url https://COMPANY.ghe.com/api`.

I kicked off the migration script. The repo archive/metadata export appears to work fine. I was able to have it upload to a mock azure storage service (`azurite`) running locally.

However, the tool did not proceed with the migration on the GHAE side, giving the following error:

```
[11:31] [DEBUG] HTTP POST: https://COMPANY.ghe.com/api/graphql
[11:31] [DEBUG] HTTP BODY: {"query":"mutation createMigrationSource($name: String!, $url: String!, $ownerId: ID!, $type: MigrationSourceType!) { createMigrationSource(input: {name: $name, url: $url, ownerId: $ownerId, type: $type}) { migrationSource { id, name, url, type } } }","variables":{"name":"GHEC Source","url":"https://github.com","ownerId":"MDEyOk9yZ2FuaXphdGlvbjExNjY2","type":"GITHUB_ARCHIVE"},"operationName":"createMigrationSource"}
[11:31] [DEBUG] GITHUB REQUEST ID: 4AA0:0023:16A7D4:330268:63572E62
[11:31] [DEBUG] RESPONSE (OK): {"errors":[{"path":["mutation createMigrationSource","createMigrationSource","input","accessToken"],"extensions":{"code":"missingRequiredInputObjectAttribute","argumentName":"accessToken","argumentType":"String!","inputObjectType":"CreateMigrationSourceInput"},"locations":[{"line":1,"column":138}],"message":"Argument 'accessToken' on InputObject 'CreateMigrationSourceInput' is required. Expected type String!"}]}
[11:31] [ERROR] System.NullReferenceException: Object reference not set to an instance of an object.
```

I am not sure whether this is relating to the fact our GHAE is not yet running 3.4.x, or whether its due to the source code assuming `github.com`: https://github.com/github/gh-gei/blob/0e7883f505db6c7eb8553100e80ab6597f64a11f/src/Octoshift/GithubApi.cs#L234

**Comment by dylan-smith** [comment]
Hi @lmk-anz we don't currently support migrations to GHAE. We have another issue #530 tracking this work.

We actually began working on making the changes necessary a while ago, then stopped the work as we realized that GHAE is running an older version of the GEI backend that isn't compatible with modern versions of this CLI.

We may revisit in the future, but we don't have any immediate plans to add support.

**Comment by dylan-smith** [comment]
I should clarify that when I say it's not supported I means specifically within this CLI. The GEI API's do support migration to GHAE and are documented here: https://docs.github.com/en/early-access/enterprise-importer/migrating-repositories-with-github-enterprise-importer/migrating-repositories-to-github-ae

**Comment by dylan-smith** [comment]
I believe that you can use the GQL API's to migrate to GHAE even on the version you are on today, however you are right that the GHES -> GHAE scenario is not documented, but I believe it will work today (not tested).

If/when GHAE gets updated enough so the API schema matches what is on github.com we could come back and update the CLI to support this scenario. But that work is not currently planned, and has alot of other competing priorities. @timrogers is our PO that ultimately owns those priority decisions.

**Comment by dylan-smith** [comment]
My understanding is that the GQL mutations are there, but the schema is older than what is on github.com which is why the CLI won't work against it. When we looked at adding support for this to the CLI we didn't think about that until we ran into it, and that was why we put the work on the shelf, because having to support multiple GQL schema's in the CLI was more work than we were ready to take on at the time.

**Comment by igorcosta** [comment]
@lmk-anz  were you able to use the old schema with that mutation?

**Comment by igorcosta** [comment]
> @igorcosta unfortunately, our GHAE instance is not providing any migration-related graphQL mutations -- I am following up with our Github support team on this.

Thanks, @lmk-anz once you sort that out, could you share try the call and see the outputs and logs generated? That would be helpful to understand how you're making the call and the outputs from our side.

Cheers

**Comment by timrogers** [comment]
I am going to close this issue because migrations to AE are not supported in the `gh gei` CLI. We have other issues open elsewhere where we are working actively to figure out the issues you're having with the API.
