### ISSUE TITLE
Error if no PAT provided

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#704]
We had a customer support ticket here: https://github.com/github/migration-friction/issues/723 where the root cause was they typo'd the env var name for GH_PAT.  However the CLI didn't appear to give any errors, and it took everybody a long time to figure out the root cause was a simple typo in the env var name.

Let's make sure that if we expect a PAT, that it is provided either in a CLI arg or an env var, and if not we fail fast and give a useful error message.

**Comment by dylan-smith** [comment]
It's possible that we already do this, but from that support ticket it suggests that we don't. It's possible the customer had both the correctly named env var and an incorrectly named env var set. but the correctly named env var had the wrong value set. Not much we can do from the CLI in that case. But we should definitely investigate and make sure the CLI is doing the right thing here.

**Comment by timrogers** [comment]
I'm going to close this one as I'm pretty convinced that we do have adequate PAT validations. Here's some output that proves it:

```
gh gei migrate-repo --source-repo airports --github-target-org avocado-corp
[12:45] [INFO] You are running the latest version of the gei CLI [v0.31]
[12:45] [ERROR] GH_PAT environment variable is not set.
```
