### ISSUE TITLE
Output URL to migration-log

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#706]
We've noticed not nearly enough customers know to go look at the migration log in the issue in the target repo. This often contains valuable information, especially in the case of a failure where it may contain more detailed messages about the cause of the failure.

One thing we could do to make it more likely customers know to look there, is after a migration completes the CLI can output the URL of the migration log issue to direct the user to go look at it.

We should add this extra output message to `migrate-repo` when run in the mode where it waits for the migration to finish (note: we have another issue open to change the default mode for migrate-repo to wait), and also add the message to `wait-for-migration` command.

**Comment by dylan-smith** [comment]
Should probably do this for both `migrate-repo ... --wait` and `wait-for-migration` command

**Comment by ArinGhazarian** [comment]
I added a [comment](https://github.com/github/gh-gei/pull/808#discussion_r1102179481) in the PR about whether we need to spit out the migration log url or we can just mention that they can download the migration log using the `download-logs` command! or maybe it's better to do both. What do you think @dylan-smith and @timrogers ?
