### ISSUE TITLE
Scope error in migrate-repo during CreateMigrationSource call 

### ISSUE THREAD

**Issue by rbanks54** [github/gh-gei#708]
## Description

I'm getting a scope permission error during a call the GetMigrationSource, and either the error message is misleading or there's a problem I can't see.

```
[4:40 PM] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":null},"errors":[{"type":"FORBIDDEN","path":["createMigrationSource"],"locations":[{"line":1,"column":109}],"message":"rbanks54 does not have the correct permissions to execute `CreateMigrationSource` query. It requires the following scopes: ['read:org', 'repo'], but the token has only been granted the: ['read:org', 'repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."}]}
```

The token needs `['read:org', 'repo']`, and has `['read:org', 'repo']`, yet an error is thrown.

## Reproduction Steps

> \> gh --version
gh version 2.17.0 (2022-10-04)
> \> gh ado2gh --version
[4:46 PM] [INFO] You are running the latest version of the ado2gh CLI [v0.29]
0.29

1. Set the ADO_PAT, and GH_PAT environment variables
2. execute `gh ado2gh migrate-repo --ado-org "<AzDO>" --ado-team-project "<PROJ>" --ado-repo "<AzDO-Repo>" --github-org "<GH>" --github-repo "<GH-Repo>" --wait --verbose`

**Comment by rbanks54** [comment]
Note: I can work around this by giving the token all org permissions, as well as the workflow permission (needed later in the process).

**Comment by timrogers** [comment]
@rbanks54 Thanks for reaching out! The error message coming from the API is a bit confusing - we're working on that now. Do you have SSO enabled on the destination organization? Are you an owner of that organization, or did someone grant you the migrator role?

**Comment by dylan-smith** [comment]
The fact that adding all scopes fixed the problem suggests to me that it is in fact a scope problem. @rbanks54 are you able to file a support ticket? that way somebody on our on-call team will dig into what's going on.

**Comment by timrogers** [comment]
@dylan-smith You might be right actually - I wasn't sure that "all org permissions" meant scopes, but on re-reading, that makes sense (tell us if we're wrong @rbanks54!).

**Comment by rbanks54** [comment]
Yes, all org permissions meant all the org scopes. 🙂

**Comment by rbanks54** [comment]
@timrogers yes, I've got SSO enabled, with tokens authorised, and I've got full permissions to both AzDO and GH.

**Comment by timrogers** [comment]
Thanks @rbanks54 🤝 If you could file a support ticket, that would be great. Sure we can take a look and figure out what's going on here.

**Comment by xiaonile** [comment]
Closing this in favor of https://github.com/github/migration-friction/issues/762 for tracking.

**Comment by timrogers** [comment]
⏫  FYI to any readers, this is now being handled as a support ticket since it doesn't appear to be an issue with the CLI specifically
