### ISSUE TITLE
No help for migrate-org command

### ISSUE THREAD

**Issue by robandpdx** [github/gh-gei#710]
## Description
Running `gh gei migrate-org --help` produces no output. I expect to see a message similar to what I see when running `gh gei migrate-repo --help`.

## Reproduction Steps
Run `gh gei migrate-org --help` on the command line. Observe no useful output message.

**Comment by dylan-smith** [comment]
good catch! that command has been present in the CLI for a while now but "hidden". With org-to-org migrations now being more widely available we should change that.
