### ISSUE TITLE
Align AWS cli args and environment vars to aws cli

### ISSUE THREAD

**Issue by robandpdx** [github/gh-gei#738]
## Description

Currently the `migrate-repo` command supports the following cli args:
`--aws-access-key <aws-access-key>`
`--aws-secret-key <aws-secret-key>`

... or the following environment variables:
`AWS_ACCESS_KEY`
`AWS_SECRET_KEY`

AWS cli uses the following environment variables:
`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY`

To make this more familiar to AWS users, it would be best to align these cli arg and environment variables to the environment variables that the aws cli uses.

Please add support for the following cli arg:
`--aws-access-key-id <aws-access-key-id>`
`--aws-secret-access-key <aws-secret-access-key>`

Please also add support for the following environment variables:
`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY`

Please update the gei cli help message for the `migrate-repo` command to reflect these new preferred args and environment variables. Please also update the early access documentation.

** Please do not remove support for the existing cli args and environment variables because these might be in use by customers who are migrating now. Best to add support for the new stuff, update the docs, and wait until a time when most users who might be migrating now are done. Only then, make the breaking change to remove support for the existing cli args and environment variables.

**Comment by timrogers** [comment]
Fixed by #855.
