### ISSUE TITLE
migrate-repo: output references Azure when AWS S3 bucket is used

### ISSUE THREAD

**Issue by DI-DaveGoodine** [github/gh-gei#740]
## Description
When migrating a repo from GHES to a github.com org, using AWS S3, the output of gei references azure blob storage.

```
[10:24 PM] [INFO] Uploading archive 2022-11-16_22-24-14-9-git_archive.tar.gz to AWS S3
[10:24 PM] [INFO] Uploading archive 2022-11-16_22-24-14-10-metadata_archive.tar.gz to AWS S3
[10:24 PM] [INFO] Archives uploaded to Azure Blob Storage, now starting migration...
```

## Reproduction Steps
1. Setup migration: create s3 bucket, create user with api keys, create source and destination PAT.
2. Issue migrate repo command `gh gei migrate-repo --github-source-org TF-Modules --github-target-org enverus-cts --source-repo tf_module_eks --target-repo sre.tf-modules.eks --ghes-api-url https://git.drillinginfo.com/api/v3 --aws-bucket-name enverus-cts-github-enterprise-importer --wait`
3. observe output.

**Comment by timrogers** [comment]
Thanks for reporting this! Great spot ❇️
