### ISSUE TITLE
[Bug] Incorrect logic in conditional param check for reclaiming mannequin-user

### ISSUE THREAD

**Issue by bobby-lin** [github/gh-gei#748]
https://github.com/github/gh-gei/blob/58aa52970cd8f4043e8deca1cfd85014dcbde0e8/src/Octoshift/Handlers/ReclaimMannequinCommandHandler.cs#L35

The correct behavior should be:
- If user don't use `csv` but includes both `mannequin-user` and `target-user`, then it should be valid.

But the code is using incorrect conditional check.

If we don't use csv param, it will always return false.

Recommended fix:
```
 if (string.IsNullOrEmpty(args.Csv) || (string.IsNullOrEmpty(args.MannequinUser) && string.IsNullOrEmpty(args.TargetUser))) 
```

**Comment by jason-dour-e** [comment]
Same issue as #760 ; different possible fix. See comments in #760 .

**Comment by timrogers** [comment]
Closing in favour of #760 - we're looking to get this one fixed shortly.
