### ISSUE TITLE
Eliminate cloud storage when migrating from GHES 3.8+

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#752]
When the source is GHES 3.8 there will no longer be a need to provide cloud storage args to the CLI (they will be configured directly in GHES). This presents a challenge for the CLI as we still need to support customers migrating from GHES 3.7 and earlier, so we now need to have different code paths and different args depending on the GHES source version.

This batch is written under the assumption that in GHES 3.8+ alambic will no longer be used, and the migration URL's returned will always be cloud storage URL's that can be directly passed to the backend. If this turns out not to be true, and we continue to support alambic in 3.8+ then the tasks below will change a bit, as we will no longer be able to determine the code path to take based on the GHES version, but will instead need to inspect the URL returned from GHES to determine whether it's using alambic or cloud storage.

## Tasks

- [x] #753
- [x] #754
- [x] #755
- [ ] #756
- [x] #770

## Dependencies

- https://github.com/github/octoshift/issues/5736

**Comment by brianaj** [comment]
Closing out as last item was moved to a backlog batch of work in https://github.com/github/octoshift/issues/5741
