### ISSUE TITLE
Internal error when creating migration source

### ISSUE THREAD

**Issue by ejdre-vestas** [github/gh-gei#777]
## Description

Hello, I have been trying to migrate a Bitbucket repository into Github and it is always failing on the `createMigrationSource` operation with an `Internal` error:
```json
{"data":{"createMigrationSource":null},"errors":[{"type":"INTERNAL","path":["createMigrationSource"],"locations":[{"line":1,"column":109}],"message":"Something went wrong while executing your query. Please include `B9B5:F003:BC89CD3:BF4C306:63BF3D06` when reporting this issue."}]}
```

## Reproduction Steps
```
gh bbs2gh migrate-repo --github-org "vestas-power-solutions" --github-repo "VOT-vot" --archive-path "{LOCAL_ARCHIVE_PATH}" --azure-storage-connection-string="{AZURE_CONNECTION_STRING}"
```

**Comment by dylan-smith** [comment]
Bitbucket migrations are not publicly available yet. We’re developing this CLI part of it as open source, but you need a feature flag turned on in your GitHub org to use it, and we’re not ready to turn that on for customers just yet.

**Comment by timrogers** [comment]
@ejdre-vestas I can let you know once Bitbucket Server migrations are available to customers as part of a beta program - can you send me an email at timrogers@github.com?
