### ISSUE TITLE
gh-gei: bbs2gh fails to run createMigrationSource

### ISSUE THREAD

**Issue by derwasp** [github/gh-gei#814]
I have raised a support request with GitHub, but I figured putting this out here might help people googling for this issue, too. And maybe this is the way I should've taken in the first place :)
The support issue has the full log if you need it.

## Description

I am trying to run GitHub Enterprise Importer for Bitbucket.
https://github.com/github/gh-gei/tree/main/src/bbs2gh

And while most of the logic is running fine, import is failing at the end.

## Reproduction Steps

I am running the latest version and this is the command:

```
  gh bbs2gh migrate-repo \
    --bbs-server-url "http://internal.bitbucket.server.com:7990" \
    --bbs-project "XXX" \
     --bbs-repo "YYY" \
     --ssh-user "QQQ" \
     --ssh-private-key "/Users/dzhuravel/.ssh/id_ed25519_cbc" \
     --ssh-port 22 \
     --github-org "MyOrg-dev" \
     --github-repo "derwasp-YYY-migrated" \
     --aws-bucket-name "derwasp-bucket-2023" \
     --aws-access-key $ak \
     --aws-secret-key $sk \
     --bbs-shared-home '/var/lib/bitbucket-home/shared' \
     --wait
```
Most of the commands succeed, but when it comes to importing the archive, this is the exception I see in the logs:

```
[13:20] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":null},"errors":[{"type":"INTERNAL","path":["createMigrationSource"],"locations":[{"line":1,"column":109}],"message":"Something went wrong while executing your query. Please include `87FE:5128:2104E8A:2193B12:63EB7CA1` when reporting this issue."}]}
```

It seems like request is going to this GraphQL endpoint and it's failing there :shrug:
https://docs.github.com/en/graphql/reference/mutations#createmigrationsource

I tried calling this same endpoint via `gh cli`:

```
I just tried reproducing this with a simple api call and it seems like I am getting the exact same result.

I ran this command via the GitHub CLI authenticated as me:

gh api graphql --paginate -f query='
   mutation createMigrationSource
   { 
      createMigrationSource(input: {name: "Bitbucket Server Source", url: "https://not-used", ownerId: "XXXXXX", type: BITBUCKET_SERVER}) 
      { 
         migrationSource { id, name, url, type } 
      } 
   }
'
```

which resulted in the same response:

```
gh: Something went wrong while executing your query. Please include `9E7B:2372:231BF18:23BA590:63EB89DD` when reporting this issue.
{
  "data": {
    "createMigrationSource": null
  },
  "errors": [
    {
      "type": "INTERNAL",
      "path": [
        "createMigrationSource"
      ],
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "message": "Something went wrong while executing your query. Please include `9E7B:2372:231BF18:23BA590:63EB89DD` when reporting this issue."
    }
  ]
}
```

However if I use `GITHUB_ARCHIVE` instead of `BITBUCKET_SERVER` it actually doesn't crash.
```
   mutation createMigrationSource
   {
      createMigrationSource(input: {name: "GHEC Source", url: "https://github.com", ownerId: "XXXXX", type: GITHUB_ARCHIVE})
      {
         migrationSource { id, name, url, type }
      }
   }
'
```

Do I need a feature flag enabled for this to work by any chance?
Or is there something else I am missing?

**Comment by timrogers** [comment]
@derwasp Per the [docs](https://docs.github.com/en/early-access/enterprise-importer/migrating-repositories-with-github-enterprise-importer/migrating-repositories-from-bitbucket-server-to-github-enterprise-cloud), Bitbucket Server migrations are in private beta, so you would need a feature flag turned on. Can you drop me an email at timrogers at github dot com?

**Comment by timrogers** [comment]
(We can look at adding you to the beta!)

**Comment by derwasp** [comment]
@timrogers thank you for the lightning-fast response team! I just dropped you a message from my work email, looking forward to chatting there!
