### ISSUE TITLE
bbs2gh: bitbucket export progress is always 50%

### ISSUE THREAD

**Issue by derwasp** [github/gh-gei#821]
## Description

It seems like no matter where we are in the export, it would always show that it's 50%
<img width="402" alt="image" src="https://user-images.githubusercontent.com/10754345/219431770-5ccc2fca-8a6b-4cb6-b75b-11c76edf47c1.png">

Not sure if this is by design or not.

**Comment by timrogers** [comment]
I think that this comes from the Bitbucket Server instance itself, so there isn't very much we can do about it 😦 I will double check that though.

**Comment by timrogers** [comment]
Confirmed that the percentage comes from Bitbucket Server: https://github.com/github/gh-gei/blob/741865e66c3d0267018c9e379b7ce99b63bb7ac4/src/bbs2gh/Handlers/MigrateRepoCommandHandler.cs#LL126C79-L126C79. I have seen it return meaningful values, so think your particular repo is maybe just being a bit weird.
