### ISSUE TITLE
Add `--keep-archive` option for GHES migrations to keep the archive on the user's machine

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#831]
When running a migration from GitHub Enterprise Server, we use the GHES API to generate an archive and then we upload that archive to the user's blob storage provider.

The API is not stored on the user's disk - which is great! - but it would be helpful to have an option to optionally keep the archive for the case where the customer wants to share it with us for debugging reasons.

We should add an optional `--keep-archive` option for GHES migrations which leaves the archive stored on user's machine. By default, we should continue to not store the archive.

**Comment by spindev** [comment]
@timrogers See #875 please.
