### ISSUE TITLE
Make the `--aws-region` arg required

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#857]
As part of adding support for AWS session token auth, we also added the `--aws-region` arg that is currently required to set if `--aws-session-token` is set. Right now for backward compatibility it's not required on its own but if it's not set, we spit out a warning to let the users know that they need to pass it as it will become required in future. Once we make sure that it's safe to make it required, we should do so and add the necessary changes in our code.  

## Todo
- [ ] Make the `--aws-region` arg required.

**Comment by timrogers** [comment]
Fixed in https://github.com/github/gh-gei/pull/1055
