### ISSUE TITLE
Provide an easy way to apply a common mapping across mannequins

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#863]
`gh gei generate-mannequin-csv` combined with `gh gei reclaim-mannequin` allows you to reclaim mannequins created from migrations en masse.

In some cases, you want to apply a simple mapping across all users - for example, user `timrogers` in the source might become `timrogers_acme`. The same might apply to all other users - e.g. `dylan-smith` -> `dylan-smith_acme`.

It would be valuable for some customers for us to build a simplified experience for doing these kinds of bulk mannequin claims that doesn't involve creating a big CSV and filling it in.

**Comment by dylan-smith** [comment]
IMO letting customers do this manipulation in a CSV (using excel or whatever) is the right approach. That way they can add suffix, prefix, do character replacements, whatever transformations they need without us need to add a bunch of transformation options.
