### ISSUE TITLE
Allow the host for SSH connections to be configured in `gh bbs2gh`

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#873]
`gh bbs2gh` can automatically connect to a Bitbucket Server instance using SSH to download the migration archive generated using the Bitbucket Server REST API.

Currently, our code assumes that the same hostname should be used for the SSH connection as the HTTP(S) connection to the REST API. This may not be the case - for example, the Bitbucket Server's UI and REST API may be exposed through a reverse proxy.

We should add an explicit `--ssh-host` option to allow the SSH host to be configured directly - though we would continue to default to the current behaviour of using the host from the `--bbs-server-url`.

This issue was reported by a customer who was unable to use the CLI due to this limitation.

## Todo

- [ ] ...

## Dependencies

- ...

**Comment by bzanin-wdc** [comment]
I would love for this option to be unhidden.  Would have saved us a few hours of unnecessary working-around if we had been able to find the option!  (Delighted to learn about it now, though.)

**Comment by timrogers** [comment]
See https://github.com/github/gh-gei/pull/874#issuecomment-1536200359 for my review to the above comment 👼🏻
