### ISSUE TITLE
Calling `bbs2gh migrate-repo` with `--bbs-server-url` but without `--bbs-project` and/or `--bbs-repo` can start an export of multiple repos

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#876]
## Description

Calling `gh bbs2gh migrate-repo` with a `--bbs-server-url` but without a `--bbs-project` and/or `--bbs-repo` causes an export to start on the Bitbucket Server including multiple repos.

* If you specify neither `bbs-project` nor `bbs-repo`, an archive will be gneerated including all repos on the server.
* If you specify a `bbs-project` but not a `bbs-repo`, all repos inside the specific project will be exported.

This isn't very helpful - GEI only supports importing a single repo, and creating such a large export can be dangerous for a Bitbucket Server instance, consuming resources until the disk becomes full.

We should validate that a `--bbs-project` and `--bbs-repo` is always provided.

## Reproduction Steps

```bash
gh bbs2gh migrate-repo --bbs-server-url https://timrogers-bitbucket.expert-services.io --ssh-user
 timrogers --ssh-private-key ~/.ssh/bbs --verbose
```

```bash
gh bbs2gh migrate-repo --bbs-server-url https://timrogers-bitbucket.expert-services.io --ssh-user timrogers --ssh-private-key ~/.ssh/bbs --verbose --bbs-project OS
```

**Comment by timrogers** [comment]
The cause of this issue seems to be the default args here: https://github.com/github/gh-gei/blob/d8c22ead501209bd3f9d52cf5b619be9b1ccdae8/src/Octoshift/BbsApi.cs#L30.

Presumably this design was intentional at some point, but it doesn't make sense because GEI can only import one repo. We should remove this default and add validations at the command level.

**Comment by ArinGhazarian** [comment]
@timrogers as you suspected this was by design and so far we have let the users decide what they want to do. Of course we can change this and raise an error.

**Comment by timrogers** [comment]
I do think we should raise an error. 

Allowing people to export everything doesn't make sense because we only support single repos on the import side (as far as I know anyway!). 

Even if we did want to support this flow, I don't think it should be the default as it can be quite dangerous for the BBS instance if you export everything!

What do you think?

**Comment by ArinGhazarian** [comment]
@timrogers totally agree with you 👍

**Comment by timrogers** [comment]
No need to drop everything, but this can be the next thing on the BBS backlog ❤️
