### ISSUE TITLE
azure-storage-connection-string no longer available when generating script

### ISSUE THREAD

**Issue by Ryan-vdw** [github/gh-gei#878]
## Description
When trying to generate a script with the flag `--azure-storage-connection-string` I get an error `Unrecognized command or argument '--azure-storage-connection-string'.`

When running `gh gei generate-script -h` The Azure flag is no longer there, only AWS.

### Versions
`You are running the latest version of the gei CLI [v0.35]`
`gh version 2.24.3 (2023-03-09)`

Note:
This is not a blocker for me as I can just modify the ps1 file and add the connection string there manually (find and replace)

## Reproduction Steps
Run:
```
gh gei generate-script \
--github-source-org {SOURCE_ORG} \
--github-target-org {TAGRGET_ORG} \
--ghes-api-url https://{HOST}/api/v3/ \
--azure-storage-connection-string '{AZURE_CONNECTION_STRING}' \
--output migration.ps1
```

Throws the following Error:
```
Unrecognized command or argument '--azure-storage-connection-string'.
Unrecognized command or argument '{REMOVED_CONNECTION_STRING}'.
```

**Comment by timrogers** [comment]
@Ryan-vdw Thanks for reaching out! 

This is actually intentional on our side to avoid having sensitive credentials like an Azure connection string stored in a script file - storing that in a file isn't a great security practice.

You can use the `AZURE_STORAGE_CONNECTION_STRING` environment variable instead. Does that make sense?

**Comment by Ryan-vdw** [comment]
Hi yes,

Thank you, that makes more sense.

Just for reference for any future travellers to this post:

```sh
export AZURE_STORAGE_CONNECTION_STRING="AZURE_CONNECTION_STRING"
```
then run your migration script
