### ISSUE TITLE
Failed to migrate from github.com to enterprise github

### ISSUE THREAD

**Issue by Rajendra08** [github/gh-gei#894]
Goal: Migrate repository from github.com/<org> to enterprize github server.
I have installed gh CLI tool and installed ghe extension.

export GH_PAT="TOKEN" (Enterprise github server PAT)
export GH_SOURCE_PAT="TOKEN"  (github.com PAT)

 gh gei migrate-repo --github-source-org https://github.com/<org> --source-repo <reponame> --github-target-org <enterprise github address> --target-repo <reponame>

[17:09] [INFO] You are running the latest version of the gei CLI [v0.36]
[17:09] [INFO] Migrating Repo...
[17:09] [INFO] GITHUB SOURCE ORG: ****
[17:09] [INFO] SOURCE REPO: ***
[17:09] [INFO] GITHUB TARGET ORG: ***
[17:09] [INFO] TARGET REPO: ***
[17:10] [ERROR] Failed to lookup the Organization ID for organization '<target Repo Address>'

May I know issue here?

**Comment by timrogers** [comment]
Hi @Rajendra08! Thanks for reaching out. 

`gh gei` does not support migrations _to_ GitHub Enterprise Server at this time. You can learn more about what migration paths we support in the docs [here](https://docs.github.com/en/migrations/using-github-enterprise-importer/understanding-github-enterprise-importer/migration-support-for-github-enterprise-importer#about-migration-support-for-github-enterprise-importer).

To migrate from GitHub.com to GHES, `ghe-migrator` is the tool you'll need to use: https://docs.github.com/en/migrations/using-ghe-migrator/exporting-migration-data-from-githubcom.
