### ISSUE TITLE
Error in migration after upgrading github enterprise to 3.8

### ISSUE THREAD

**Issue by solankiarpan** [github/gh-gei#914]
## Description

I am seeing the following error.

Git archive URL returned a HTTP 400 response. Please make sure that the URL is valid and that the file is accessible.
There is3 bucket set in the console.
I am seeing objects being uploaded to s3 bucket. So there does not seem to be AWS Credentials issue.

## Reproduction Steps
gh gei migrate-repo --github-source-org "sourceorg" --source-repo "sourcerepo" --target-repo "targetrepo" --github-target-org "orgname" --ghes-api-url "apiurl" --wait --verbose

**Comment by timrogers** [comment]
Closing this issue as it relates to the GitHub Enterprise Importer backend rather than the CLI, and I am supporting @solankiarpan directly.
