### ISSUE TITLE
Implement `gh bbs2gh inventory-report` command for generating Bitbucket Server repo inventory

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#955]
When customers are planning and preparing their migration, it's really valuable to create a "migration inventory" with key data about all of the repos to be migrated. We recommend doing this in our [public docs](https://docs.github.com/en/migrations/overview/planning-your-migration-to-github).

At this time, for Bitbucket Server, we don't have a tool we can recommend for generating this kind of report.

We should build a `gh bbs2gh inventory-report` command which can generate a report on a customer's Bitbucket Server repos.

It should output a CSV with the following data:

* name
* project_key
* is_archived
* pull_requsts_count
* last_commit_at

Its interface should:

* Require a `--bbs-server-url` to be specified as an argument*
* Authenticate with `--bbs-username` and `--bbs-password` (same as other API calls and `gh-bbs-analyzer`)
* Require a `--output-path` to be specified as an argument to define where the CSV should be stored (match on behavior of other `inventory-report` commands)
* Optionally allow a `--bbs-project` to be specified to limit the output to repos in one specific Bitbucket Server project

_*Or environment variable; check what existing code does_

Under the hood, it will need to use the following Bitbucket Server APIs with auto-pagination:

* ["Get projects"](https://developer.atlassian.com/server/bitbucket/rest/v809/api-group-project/#api-api-latest-projects-get) to find all projects, if the command is not limited to a specific project using `--bbs-project`
* ["Get repositories for project"](https://developer.atlassian.com/server/bitbucket/rest/v809/api-group-project/#api-api-latest-projects-projectkey-repos-get) to list repos in each project
* ["Get pull requests for repository"](https://developer.atlassian.com/server/bitbucket/rest/v809/api-group-pull-requests/#api-api-latest-projects-projectkey-repos-repositoryslug-pull-requests-get) to get the count of pull requests for a repo
* ["Get commits](https://developer.atlassian.com/server/bitbucket/rest/v809/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-commits-get) to get the last commit timestamp for a repo

### Example repository API response

```json
{"size":1,"limit":25,"isLastPage":true,"values":[{"slug":"litra","id":1,"name":"litra","description":"A JavaScript library for programatically controlling your Logitech Litra Glow or Logitech Litra Beam light - including CLI tools for quick usage without writing code","hierarchyId":"e9b26cb584a595f3cfa0","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"OS","id":1,"name":"Open Source","public":false,"type":"NORMAL","links":{"self":[{"href":"https://timrogers-bitbucket.expert-services.io/projects/OS"}]}},"public":false,"archived":false,"links":{"clone":[{"href":"ssh://git@timrogers-bitbucket.expert-services.io/os/litra.git","name":"ssh"},{"href":"https://timrogers-bitbucket.expert-services.io/scm/os/litra.git","name":"http"}],"self":[{"href":"https://timrogers-bitbucket.expert-services.io/projects/OS/repos/litra/browse"}]}}],"start":0}
```

## Tasks

- [ ] ...

## Dependencies

- ...

**Comment by stebje** [comment]
+1 for this functionality 👍 

💡 **Suggestion**: the `csv` will potentially contain a large number of repos, and in most cases this list will need to be split into batches unless all repos are migrated in one go. With that in mind it would be great to include some more metadata that will make the `csv` more "reader-friendly", e.g. 
- `repo_description`
- `project_description`

If possible, it would also be beneficial to include the (approximate) repo size, as an early indicator of repos that might need to be cleaned up before the migration. At first glance it does not look like this is supported in the BBS API but I might be wrong.

cc @dylan-smith

**Comment by KittyChiu** [comment]
@samueljmello has built something similar for [Manulife](https://github.com/github/beta-tracking/issues/2078) https://github.com/mona-actions/gh-bbs-analyzer
