### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by ianlistopad-8451** [github/gh-gei#967]
I am looking for the functionality of the --target-repo-visibility, #953. I was wondering what the guidelines were or how I can go about getting a new version created to use all of the functionalities that have been merged since v 0.40 was published. Thanks!

**Comment by timrogers** [comment]
Thanks for reaching out! 👋 We should be able to ship a new version tomorrow to get this change out 😊

**Comment by timrogers** [comment]
Shipped! https://github.com/github/gh-gei/releases/tag/v0.41
