### ISSUE TITLE
Re-implement `gh-migration-analyzer` as `gh gei inventory-report`

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#993]
Our great [`gh-migration-analyzer`](https://github.com/github/gh-migration-analyzer) open source project is a CLI tool which helps you to plan your GitHub migration by creating a CSV "inventory" of repos in a GitHub organization.

But having this tool inside the `gh gei` CLI would make it much more easily accessible to customers, without having to download another tool or set up Node.js.

It'll also be more maintainable for us - we don't have strong JavaScript expertise within the Migration Tools team!

Let's bring its functionality in `gh gei`! 🥳 

We should add a `gh gei inventory-report` command, like the existing command in `gh ado2gh`, which takes the organization and GitHub API URL as arguments and generates a CSV with a format like the following:

```csv
organization,repository_name,last_pushed_at,is_archived,pull_requests_count,issues_count,releases_count,disk_usage_in_bytes
```

**Comment by dylan-smith** [comment]
this is probably a duplicate of #493

**Comment by timrogers** [comment]
@dylan-smith Good spot! I did see it, but was thrown off by the `repo-list` bit. I might close that one and split it into two distinct issues.

**Comment by timrogers** [comment]
Closing in favour of https://github.com/github/gh-gei/issues/493
